apiVersion: v1
kind: Service
metadata:
  name: md-svc
spec:
  selector:
    app: md
  ports:
    - protocol: TCP
      name: ngiinx
      port: 80
      targetPort: 80
    - protocol: TCP
      name: multitool
      port: 8080
      targetPort: 1180